"""CDK infrastructure code generation for modern Lambda functions.

Requirements: 6.7
"""

from rosetta_zero.models.logic_map import LogicMap
from rosetta_zero.utils.logging import logger


def generate_cdk_infrastructure(logic_map: LogicMap, lambda_code: str) -> str:
    """
    Generate AWS CDK infrastructure code for the modern Lambda implementation.
    
    Args:
        logic_map: Logic Map defining the system
        lambda_code: Generated Lambda function code
        
    Returns:
        CDK Python code defining infrastructure
    """
    artifact_id = logic_map.artifact_id
    artifact_version = logic_map.artifact_version
    
    # Determine required AWS resources from Logic Map
    requires_s3 = any(se.operation_type.value == "FILE_IO" for se in logic_map.side_effects)
    requires_dynamodb = any(se.operation_type.value == "DATABASE" for se in logic_map.side_effects)
    requires_vpc = any(se.operation_type.value == "NETWORK" for se in logic_map.side_effects)
    
    cdk_code = f'''"""
CDK Infrastructure for {artifact_id} v{artifact_version}

Auto-generated by Rosetta Zero Bedrock Architect.
"""

from aws_cdk import (
    Stack,
    Duration,
    RemovalPolicy,
    aws_lambda as lambda_,
    aws_iam as iam,
    aws_logs as logs,
    aws_s3 as s3,
    aws_dynamodb as dynamodb,
    aws_ec2 as ec2,
    aws_kms as kms,
)
from constructs import Construct


class {_to_class_name(artifact_id)}Stack(Stack):
    """CDK Stack for {artifact_id} modern implementation."""
    
    def __init__(self, scope: Construct, construct_id: str, **kwargs):
        super().__init__(scope, construct_id, **kwargs)
        
        # KMS key for encryption
        self.kms_key = kms.Key(
            self, "EncryptionKey",
            description=f"Encryption key for {artifact_id}",
            enable_key_rotation=True,
            removal_policy=RemovalPolicy.RETAIN,
        )
'''
    
    # Add VPC if needed
    if requires_vpc:
        cdk_code += '''
        # VPC for Lambda function
        self.vpc = ec2.Vpc(
            self, "VPC",
            max_azs=2,
            nat_gateways=1,
            subnet_configuration=[
                ec2.SubnetConfiguration(
                    name="Private",
                    subnet_type=ec2.SubnetType.PRIVATE_WITH_EGRESS,
                    cidr_mask=24,
                ),
                ec2.SubnetConfiguration(
                    name="Public",
                    subnet_type=ec2.SubnetType.PUBLIC,
                    cidr_mask=24,
                ),
            ],
        )
        
        # Security group for Lambda
        self.security_group = ec2.SecurityGroup(
            self, "LambdaSecurityGroup",
            vpc=self.vpc,
            description=f"Security group for {artifact_id} Lambda",
            allow_all_outbound=True,
        )
'''
    
    # Add S3 bucket if needed
    if requires_s3:
        cdk_code += '''
        # S3 bucket for file operations
        self.data_bucket = s3.Bucket(
            self, "DataBucket",
            encryption=s3.BucketEncryption.KMS,
            encryption_key=self.kms_key,
            versioned=True,
            block_public_access=s3.BlockPublicAccess.BLOCK_ALL,
            enforce_ssl=True,
            removal_policy=RemovalPolicy.RETAIN,
        )
'''
    
    # Add DynamoDB table if needed
    if requires_dynamodb:
        cdk_code += '''
        # DynamoDB table for data storage
        self.data_table = dynamodb.Table(
            self, "DataTable",
            partition_key=dynamodb.Attribute(
                name="id",
                type=dynamodb.AttributeType.STRING,
            ),
            encryption=dynamodb.TableEncryption.CUSTOMER_MANAGED,
            encryption_key=self.kms_key,
            point_in_time_recovery=True,
            billing_mode=dynamodb.BillingMode.PAY_PER_REQUEST,
            removal_policy=RemovalPolicy.RETAIN,
        )
'''
    
    # Add Lambda function
    cdk_code += f'''
        # IAM role for Lambda function
        self.lambda_role = iam.Role(
            self, "LambdaRole",
            assumed_by=iam.ServicePrincipal("lambda.amazonaws.com"),
            managed_policies=[
                iam.ManagedPolicy.from_aws_managed_policy_name(
                    "service-role/AWSLambdaBasicExecutionRole"
                ),
'''
    
    if requires_vpc:
        cdk_code += '''                iam.ManagedPolicy.from_aws_managed_policy_name(
                    "service-role/AWSLambdaVPCAccessExecutionRole"
                ),
'''
    
    cdk_code += '''            ],
        )
        
        # Grant permissions
        self.kms_key.grant_encrypt_decrypt(self.lambda_role)
'''
    
    if requires_s3:
        cdk_code += '''        self.data_bucket.grant_read_write(self.lambda_role)
'''
    
    if requires_dynamodb:
        cdk_code += '''        self.data_table.grant_read_write_data(self.lambda_role)
'''
    
    # Lambda function definition
    vpc_config = "vpc=self.vpc,\n            security_groups=[self.security_group]," if requires_vpc else ""
    
    cdk_code += f'''
        # Lambda function
        self.lambda_function = lambda_.Function(
            self, "Function",
            runtime=lambda_.Runtime.PYTHON_3_12,
            handler="handler.lambda_handler",
            code=lambda_.Code.from_asset("lambda"),
            role=self.lambda_role,
            timeout=Duration.minutes(15),
            memory_size=3008,
            {vpc_config}
            environment={{
                "KMS_KEY_ID": self.kms_key.key_id,
'''
    
    if requires_s3:
        cdk_code += '''                "DATA_BUCKET": self.data_bucket.bucket_name,
'''
    
    if requires_dynamodb:
        cdk_code += '''                "DATA_TABLE": self.data_table.table_name,
'''
    
    cdk_code += '''            }},
            log_retention=logs.RetentionDays.SEVEN_YEARS,
        )
'''
    
    # Add outputs
    cdk_code += '''
        # Outputs
        from aws_cdk import CfnOutput
        
        CfnOutput(
            self, "FunctionArn",
            value=self.lambda_function.function_arn,
            description="Lambda function ARN",
        )
        
        CfnOutput(
            self, "FunctionName",
            value=self.lambda_function.function_name,
            description="Lambda function name",
        )
'''
    
    logger.info(
        "CDK infrastructure code generated",
        extra={
            "artifact_id": artifact_id,
            "requires_s3": requires_s3,
            "requires_dynamodb": requires_dynamodb,
            "requires_vpc": requires_vpc,
        }
    )
    
    return cdk_code


def _to_class_name(artifact_id: str) -> str:
    """Convert artifact ID to Python class name."""
    # Remove special characters and convert to PascalCase
    parts = artifact_id.replace('-', '_').replace('.', '_').split('_')
    return ''.join(word.capitalize() for word in parts if word)
